### ISSUE TITLE
Update to serde 1.0

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic-types#62]
Now that `serde` 1.0 is out we should upgrade to the stable API.

**Comment by dtolnay** [comment]
Hey maybe you noticed but I renamed serde_codegen_internals to serde_derive_internals. I decided I don't like the word "codegen" anymore because it scares people.

**Comment by KodrAus** [comment]
Ah thanks for pointing that out! I hadn't noticed, but probably would've stumbled into it eventually :)
